### ISSUE TITLE
hash-map in hm-lio compare with ikdtree in fastlio2

### ISSUE THREAD

**Issue by kahowang** [chengwei0427/hm-lio#1]
Thank you very much for your work, in hm-lio, using hash map to maintain the local map, compred with  idktree to maintain the local map in FASTLIO2, which is better? 
Thank you again for your excellent work ~

**Comment by chengwei0427** [comment]
Hi, @kahowang 
Thanks for your interesting in our work!
Fastlio2 maybe better than ours, and this is just a simple reproduction of fastlio 1.0 with Hash-map, verified it's feasibility, there is still some work that needs to be optimized.

1. use hashmap maintain local dataset based on fastlio2;
2. Optimize and add weight items
3. ...

**Comment by kahowang** [comment]
Ok, thank you for your reply ~
